### ISSUE TITLE
Sync function

### ISSUE THREAD

**Issue by kantord** [fiatjaf/jq-web#8]
Returning {} when .mem/.wasm are not loaded yet is good, but it'd be even better to have a sync call. (One that would block until the loading finished and maybe fail after a timeout)

**Comment by fiatjaf** [comment]
I would like that too, but don't know how to do it or if it is even possible. I believe it isn't possible at all, because if a function is blocking, single-threaded JavaScript can't run the other initialization steps even after .mem/.wasm finishes loading, so it will block forever.

Actually, the default solution would be to use Promises for every call, but I like the way it is now, the only problem is those calls made before the initialization process is finished. The `{}` does little harm, I guess, but we could also have a promised API for people who want zero-harm.

**Comment by kantord** [comment]
A Promise API would indeed be great!

**Comment by fiatjaf** [comment]
Ok, so how should I call these? `jq.promised()` and `jq.promised.raw()`, perhaps?

**Comment by kantord** [comment]
It's your project hahaha :-D But it looks totally fine to me :-)

**Comment by fiatjaf** [comment]
ahahah, thanks!
I believe https://github.com/fiatjaf/jq-web/commit/02ffba396319d2830c1c406878108f7f3d9f9ebd is working.
